name: Weekly Suyu Build (macOS)

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  watch: 
    types: [started]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120  # Set timeout to 2 hours

    env:
      Qt5_DIR: /opt/homebrew/opt/qt@5/lib/cmake
      LIBVULKAN_PATH: /opt/homebrew/lib/libvulkan.dylib
      LLVM_DIR: /opt/homebrew/opt/llvm@17
      FFMPEG_DIR: /opt/homebrew/opt/ffmpeg
      VULKAN_SDK: /opt/homebrew/opt/vulkan-headers      

    steps:
      - name: Checkout Repository
        run: |
          git clone --recursive https://git.suyu.dev/suyu/suyu.git .
          git checkout dev

      - name: Install Dependencies
        run: |
          brew update
          brew install \
            autoconf automake boost ccache ffmpeg fmt glslang hidapi \
            libtool libusb lz4 ninja nlohmann-json openssl pkg-config \
            qt@5 sdl2 speexdsp zlib zstd cmake Catch2 molten-vk \
            vulkan-headers vulkan-loader

      - name: Prepare Build Environment
        run: |
          mkdir -p build
          cd build

      - name: Configure CMake
        working-directory: build
        run: |
          cmake .. -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DSUYU_USE_BUNDLED_VCPKG=OFF \
            -DSUYU_TESTS=OFF \
            -DENABLE_WEB_SERVICE=OFF \
            -DENABLE_LIBUSB=OFF \
            -DSDL_ARMNEON=ON \
            -DENABLE_QT6=OFF \
            -DENABLE_QT_TRANSLATION=ON \
            -DSUYU_USE_EXTERNAL_VULKAN_HEADERS=ON \
            -DCLANG_FORMAT=ON \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DVULKAN_HEADERS_INSTALL_DIR=$(brew --prefix vulkan-headers) \
            -DCMAKE_CXX_FLAGS="-v"  # Add verbose compiler output
            
      - name: Build Suyu
        working-directory: build
        run: ninja

      - name: Bundle Dependencies
        working-directory: build
        run: |
          dylibbundler -of -cd -b -x bin/suyu.app/Contents/MacOS/suyu -d bin/suyu.app/Contents/libs/

      - name: Copy Qt5 Frameworks
        working-directory: build
        run: |
          QT_LIB_DIR=$(brew --prefix qt@5)/lib
          mkdir -p bin/suyu.app/Contents/Frameworks
          
          # Copy essential Qt5 frameworks
          qt_frameworks=(
            "QtCore"
            "QtGui"
            "QtWidgets"
            "QtNetwork"
            "QtConcurrent"
            "QtPrintSupport"
            "QtSvg"
          )
          
          for framework in "${qt_frameworks[@]}"; do
            cp -R "$QT_LIB_DIR/${framework}.framework" bin/suyu.app/Contents/Frameworks/
          done

      - name: Create DMG
        working-directory: build/bin
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Suyu" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "suyu.app" 200 190 \
            --hide-extension "suyu.app" \
            --app-drop-link 600 185 \
            "Suyu.dmg" \
            "suyu.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: suyu-macos
          path: build/bin/Suyu.dmg
          retention-days: 7

      - name: Create Release
        if: github.event_name == 'schedule'  # Only create release on scheduled runs
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/Suyu.dmg
          name: "Suyu Weekly Build $(date +'%Y-%m-%d')"
          tag_name: "weekly-$(date +'%Y-%m-%d')"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}